### PR TITLE
Add profile picture

### PR DESCRIPTION
**Pull request by shola-lawal**

### CODE REVIEW

**Comment by leafac** [comment]
Thanks for getting this started.

Please look at the comments left under your name on the staff page at `staff/index.md`. You need to follow the format for the picture (circular crop, 600x600), and fill in the rest of the data.

**Comment by shola-lawal** [comment]
I was hoping to use use css for this format?
Please advise.

**Comment by leafac** [comment]
We could have used CSS to do some formatting of the image, but we didn’t. Please follow the pattern you see in other images on the same page.

And please fill in the rest of the profile.

**Comment by shola-lawal** [comment]
@leafac, Please take a look.

**Comment by leafac** [comment]
Thanks. I made [a few changes](https://github.com/jhu-oose/www.jhu-oose.com/commit/e1858f0025cb45fe82c2a481e476f7ad0be9bd35) to make your profile consistent with the rest of the page.

**Pull request merged**
